# resolver: lts-10.5
resolver: ghc-8.0.2
packages:
- .
extra-deps: [
    tasty-1.0.0.1
  , tasty-quickcheck-0.9.2
  , tasty-hunit-0.10.0.1
  , QuickCheck-2.11.3
  , ansi-terminal-0.8.0.1
  , async-2.2.1
  , clock-0.7.2
  , mtl-2.2.1
  , optparse-applicative-0.14.0.0
  , random-1.1
  , stm-2.4.5.0
  , tagged-0.8.5
  , unbounded-delays-0.1.1.0
  , ansi-wl-pprint-0.6.8.2
  , colour-2.3.4
  , hashable-1.2.6.1
  , tf-random-0.5
  , transformers-compat-0.5.1.4
  , primitive-0.6.3.0
  , text-1.2.3.0
  , call-stack-0.1.0
  , derive-2.6.3
  , haskell-src-exts-1.19.1
  , syb-0.7
  , uniplate-1.6.12
  , cpphs-1.20.8
  , unordered-containers-0.2.9.0
  , old-locale-1.0.0.7
  , old-time-1.1.0.3
  , polyparse-1.12
  , TypeCompose-0.9.12
  , base-orphans-0.6
]
